Fix a error produced when create entity without enter a location field type and modify this entity after because oldGeo is null
if (newGeo[0] != oldGeo[0] || newGeo[1] != oldGeo[1]) {
		                       ^
TypeError: Cannot read property '0' of undefined